theme: jekyll-materialdocs
menu: menu.html # will use this as the menu item text instead of title
parent: index.md # will make this menu item a child of the index.md item
weight: 2 # smaller weights rise to the top of the menu
